# --- 1. Configuración Básica ---
set -g mouse on
set -s escape-time 0
set -g history-limit 50000
set -g status-position top

# Soporte de colores
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# --- 2. Atajos ---
bind r source-file ~/.tmux.conf \; display "¡PowerKit Recargado!"

# --- Cambio de Prefijo (Ctrl+b -> Ctrl+a) ---
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# --- NAVEGACIÓN INTELIGENTE (Vim-Tmux-Navigator) ---
# Detecta si estamos en Vim para pasarle los comandos de movimiento
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf|nano)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# Como Ctrl+l ahora mueve paneles, usamos Prefijo + Ctrl+l para limpiar la pantalla
bind C-l send-keys 'C-l'

# --- Navegación de alto nivel con Alt (Meta) ---

# Moverse entre VENTANAS (Pestañas) con Alt + h/l
bind -n M-h previous-window
bind -n M-l next-window

# Moverse entre SESIONES con Alt + j/k
bind -n M-j switch-client -p
bind -n M-k switch-client -n

# --- 3. Lista de Plugins (PowerKit) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'christoomey/vim-tmux-navigator' 
set -g @plugin 'tmux-plugins/tmux-yank'

# --- 4. CONFIGURACIÓN DE POWERKIT ---
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"
set -g @powerkit_separator_style "slant"
set -g @powerkit_plugins "datetime,git"
set -g @powerkit_plugin_git_show_files "true"
set -g @powerkit_plugin_git_show_branch "true"
set -g @powerkit_plugin_git_max_length "20"
set -g @powerkit_transparent "true"
set -g @powerkit_status_interval "1"

# --- 5. Inicializar TPM (Siempre al final) ---
run '~/.tmux/plugins/tpm/tpm'

# Empezar la numeración de ventanas y paneles en 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
# Renombrar ventanas automáticamente cuando se cierra una intermedia
set-option -g renumber-windows on

# Abrir paneles en el directorio actual
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
# Desvincular las teclas por defecto
unbind '"'
unbind %

# Activar modo Vi para el modo copia
set-window-option -g mode-keys vi

# Atajos para selección y copia en modo Vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Para rededimensionar las ventas desde teclado
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g extended-keys on
