return {
  "nvimdev/dashboard-nvim",
  lazy = false,
  priority = 999,
  dependencies = { { "nvim-tree/nvim-web-devicons" } },
  config = function()
    require("dashboard").setup({
      theme = "hyper",
      config = {
        -- Acá va tu ASCII art. Reemplazá este header con el de tu imagen.
        -- Cada string es una línea. Ejemplo:
        -- header = {
        --   [[  ██████  ]],
        --   [[ ██  ████ ]],
        --   [[dasafo.dot]],
        -- },
        header = {
          [[MMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl.,lxK0O0NWMMMMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMMMMMMXOxdoolc:,'.............,:ldOXWMMMM]],
          [[MMMMMMMMMMMMMMMMMMMM0dl:;,''''......''... ............'kMMM]],
          [[MMMMMMMMMMMWOockOd;................',''''........ ......KMM]],
          [[MMMMMMMMMWOo'.....  ................;,,'....'............OMM]],
          [[MMMMMMMWx........   ......';:;..........'..;,,'..........NMM]],
          [[MMMMMMk..  ... .   ..........'......''..;'.';c:,.......'oMMM]],
          [[MMMWk,.    ..  .   ..............',,;c:,'.''':ol......,,XMMM]],
          [[MMk..             ........... ..'.'',;;cll;,,:dO:.....;dMMMM]],
          [[W:.                 ...........';:,;;:;;;:ldo:oO0l....:0MMMM]],
          [[K                  ...........':c:;'........:xOkOW;...'kMMMM]],
          [[W'                 .,,..  ..'',::;...   ... .okk0MWl...:WMMM]],
          [[MX,                .;:'....;;,,,,,...  .. ..,ldxKMMMXdloWMMM]],
          [[MMWc               .;;;;,,::;;,''''.........':oxNMMMMMMMMMMM]],
          [[MMMM0c.             .';;;;;;;;,'''..........';ldXMMMMMMMMMMM]],
          [[MMMMMMWc             .',,;;;;;,.''...........':d0MMMMMMMMMMM]],
          [[MMMMMMMMo        .'    ..';:;;;,...'........  .:kMMMMMMMMMMM]],
          [[MMMMMMMMMk.     .0x     ..',,,,,''......';.....'oMMMMMMMMMMM]],
          [[MMMMMMMMMMWx:;ckWMK       .''..........'ckxc....lMMMMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMMc      .,;,......,'.'ckOl....;MMMMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMMN.     .;:cc:,.';;:;;cdo.....oMMMMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMMM'      .';;'.',;;:c:;;......dM00MMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMMM,        ......'',,.........ox'XMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMMX'.             ....    .......dMMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMMMX'.....            .  ...',;,''.dMMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMM0.. ......'...........,cl,cccl;'.'XMMMMMMMM]],
          [[MMMMMMMMMMMMMMMMN...  .,,'.;...,......'::c;oxx;....:WMMMMMMM]],
          [[MMMMMMMMMMMMMMMMd..     .,,....'......';,ool;.......oMMMMMMM]],
          [[MMMMMMMMMMMMMMMM;       .,;,,;:;,,,;::'.....  ... ...OMMMMMM]],
          [[MMMMMMMMMMMMMMMX..      ;;,,;;,':cclc;.     .........'KMMMMM]],
          [[MMMMMMMMMMMMMMMo.       ..'''..             ...  . ...,WMMMM]],
          [[MMMMMMMMMMMMMMW.                      .  .....   . ....lMMMM]],
          [[MMMMMMMMMMMMMM0                           ....   .......NMMM]],
        },
        shortcut = {
          { desc = "󰊳 Update", group = "@property", action = "Lazy update", key = "u" },
          { desc = " Files", group = "Label", action = "Telescope find_files", key = "f" },
          { desc = " Grep", group = "DiagnosticHint", action = "Telescope live_grep", key = "g" },
          { desc = "󰤯 Recent files", group = "Number", action = "Telescope oldfiles", key = "r" },
        },
        packages = { enable = true },
        project = { enable = true, limit = 8 },
        mru = { enable = true, limit = 10, cwd_only = false },
      },
    })
  end,
}
